apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-03-13T12:47:16Z"
  labels:
    app: nginx
  name: nginx
  namespace: default
  resourceVersion: "19146"
  uid: 13898959-5a82-42ef-90ec-73bccb99ca4f
spec:
  clusterIP: 10.107.1.185
  clusterIPs:
  - 10.107.1.185
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-80
    nodePort: 31899
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
